### ISSUE TITLE
Certain topics not showing available information

### ISSUE THREAD

**Issue by tracypholmes** [kjleitz/whatsa#8]
**Ex:** Search for dog provides "Breeding Terminology" as a specific subject. Selecting it shows 

`[no displayable information]`

However, there is information available on the [Wikipedia](https://en.wikipedia.org/wiki/Dog#Breeding_terminology) page. Is it only able to pull certain types of information?

**Comment by kjleitz** [comment]
Good catch!! That's what issues #1 and #2 are; basically, right now, it doesn't pull `<li>` tags as paragraphs because wikipedia is frustratingly inconsistent and it's hard to differentiate between list items that are in, like, tables of contents, etc. 

I may decide to remove sections with no "displayable info" at all, but I haven't structured the program to handle that yet. Shouldn't be too hard, so that's next on the docket. But also, I would _like_ to support list items that are "real" info in a section, so I haven't hidden those sections just yet.

**Comment by kjleitz** [comment]
fixed by https://github.com/kjleitz/whatsa/commit/b3bf16220ab591ccaa494b48726b06e89c7d9d6b and https://github.com/kjleitz/whatsa/commit/faf853ac516622ac58ac5959879c4ab185bf6635

Now it shows list items separated by dashes where they once were bulleted lists on Wikipedia, and sections which are weird and are just a `<div>` with crap in it are wholly thrown out because screw that seriously
